lines:
  - line_1:
    weight: 0.3
    nodes: 
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  - line_2:
    weight: 0.3
    nodes: 
      - 10
      - 11
      - 12
      - 14
  - line_3:
    weight: 0.3
    nodes: 
      - 14
      - 15
      - 16
      - 27
      - 28
      - 29
  - line_4:
    weight: 0.3
    nodes: 
      - 21
      - 23
      - 14
      - 4