lines:
  - line_1:
    weight: 0.3
    nodes: 
      - 0
      - 2
      - 4
      - 6
      - 18
      - 39
      - 59
  - line_2:
    weight: 0.3
    nodes: 
      - 20
      - 22
      - 24
  - line_3:
    weight: 0.2
    nodes: 
      - 42
      - 22
      - 2
  